image: ubuntu:16.04

variables:
  LATEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:latest

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:stable
  script:
    - touch .env
    - echo "DB_DRIVER=org.postgresql.Driver" >> .env
    - echo "DB_SERVER=postgresql" >> .env
    - echo "DB_HOST=$PROD_DB_HOST" >> .env
    - echo "DB_NAME=$PROD_DB_NAME" >> .env
    - echo "DB_USERNAME=$PROD_DB_USERNAME" >> .env
    - echo "DB_PASSWORD=$PROD_DB_PASSWORD" >> .env
    - echo "FRONT_HOST=http://aproc.urcamp.edu.br" >> .env
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $LATEST_IMAGE -f ./src/main/docker/Dockerfile .
    - docker push $LATEST_IMAGE
  only:
    - master

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --stack $RANCHER_STACK --service $RANCHER_SERVICE --new-image $LATEST_IMAGE --start-before-stopping
  only:
    - master
